/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Departments */
        get: operations["list_departments_api_v1_departments_get"];
        put?: never;
        /** Create Department */
        post: operations["create_department_api_v1_departments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/departments/{dept_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Department */
        delete: operations["delete_department_api_v1_departments__dept_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/residents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Residents */
        get: operations["list_residents_api_v1_residents_get"];
        put?: never;
        /** Create Resident */
        post: operations["create_resident_api_v1_residents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/residents/{resident_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Resident */
        patch: operations["assign_resident_api_v1_residents__resident_id__assign_patch"];
        trace?: never;
    };
    "/api/v1/residents/auto-assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Assign
         * @description Assign all active residents to angels sequentially by room (same room → same angel).
         */
        post: operations["auto_assign_api_v1_residents_auto_assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/residents/sync-pcc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Pcc
         * @description Mock PCC sync.
         */
        get: operations["sync_pcc_api_v1_residents_sync_pcc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resident-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["list_groups_api_v1_resident_groups_get"];
        put?: never;
        /** Create Group */
        post: operations["create_group_api_v1_resident_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resident-groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Group */
        delete: operations["delete_group_api_v1_resident_groups__group_id__delete"];
        options?: never;
        head?: never;
        /** Update Group */
        patch: operations["update_group_api_v1_resident_groups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/resident-groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Members
         * @description Replace the full membership list for a group.
         */
        put: operations["set_members_api_v1_resident_groups__group_id__members_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/angels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Angels */
        get: operations["list_angels_api_v1_angels_get"];
        put?: never;
        /** Create Angel */
        post: operations["create_angel_api_v1_angels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/angels/{angel_id}/absent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set Absent */
        patch: operations["set_absent_api_v1_angels__angel_id__absent_patch"];
        trace?: never;
    };
    "/api/v1/angels/{angel_id}/redistribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redistribute
         * @description Redistribute unassigned residents across the available (non-absent) angels.
         */
        post: operations["redistribute_api_v1_angels__angel_id__redistribute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qapis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Qapis */
        get: operations["list_qapis_api_v1_qapis_get"];
        put?: never;
        /** Create Qapi */
        post: operations["create_qapi_api_v1_qapis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qapis/{qapi_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Qapi */
        delete: operations["delete_qapi_api_v1_qapis__qapi_id__delete"];
        options?: never;
        head?: never;
        /** Update Qapi */
        patch: operations["update_qapi_api_v1_qapis__qapi_id__patch"];
        trace?: never;
    };
    "/api/v1/qapis/{qapi_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_qapis__qapi_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qapis/{qapi_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_qapis__qapi_id__items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_qapis__qapi_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_v1_questions_get"];
        put?: never;
        /** Create Question */
        post: operations["create_question_api_v1_questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Question */
        delete: operations["delete_question_api_v1_questions__question_id__delete"];
        options?: never;
        head?: never;
        /** Update Question */
        patch: operations["update_question_api_v1_questions__question_id__patch"];
        trace?: never;
    };
    "/api/v1/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Issues */
        get: operations["list_issues_api_v1_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Issue
         * @description Mark an issue resolved.
         *
         *     Mirrors the frontend `canResolve` guard so the API enforces it too:
         *       - admin and charge_nurse can always resolve
         *       - an angel can resolve only issues in their own department
         *     The `resolved_by` user must exist and be active. Without this check,
         *     the UI could be bypassed and an arbitrary user attributed.
         */
        post: operations["resolve_issue_api_v1_issues__issue_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Issue */
        post: operations["reopen_issue_api_v1_issues__issue_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List all templates. Phase 4.2 contract: any active RapidRound whose
         *     end_date has passed gets auto-archived on retrieval, so admins don't
         *     have to babysit a "Stop" button when the survey window naturally ends.
         */
        get: operations["list_templates_api_v1_rounds_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_v1_rounds_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_v1_rounds_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Update Template */
        patch: operations["update_template_api_v1_rounds_templates__template_id__patch"];
        trace?: never;
    };
    "/api/v1/rounds/templates/{template_id}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy Template
         * @description Push a rapid round to angels.
         *
         *     Sets `deployed_at` to NOW(). The angel rounding view filters by
         *     `deployed_at IS NOT NULL` (and type='rapid') to decide which rapid
         *     templates to bundle into the angel's queue. Only valid for rapid
         *     rounds — deploying an angel template would be meaningless since
         *     angels always see the active angel template.
         */
        post: operations["deploy_template_api_v1_rounds_templates__template_id__deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/templates/{template_id}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Section */
        post: operations["create_section_api_v1_rounds_templates__template_id__sections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Section */
        delete: operations["delete_section_api_v1_rounds_sections__section_id__delete"];
        options?: never;
        head?: never;
        /** Update Section */
        patch: operations["update_section_api_v1_rounds_sections__section_id__patch"];
        trace?: never;
    };
    "/api/v1/rounds/sections/{section_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Question To Section */
        post: operations["add_question_to_section_api_v1_rounds_sections__section_id__questions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds/template-questions/{template_question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Question From Section */
        delete: operations["remove_question_from_section_api_v1_rounds_template_questions__template_question_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rounds */
        get: operations["list_rounds_api_v1_rounds_get"];
        put?: never;
        /**
         * Submit Round
         * @description Submit a completed round. Inserts the round + answers and auto-creates
         *     issues + notifications for any flagged answers.
         */
        post: operations["submit_round_api_v1_rounds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qaa-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notes */
        get: operations["get_notes_api_v1_qaa_notes_get"];
        /** Update Notes */
        put: operations["update_notes_api_v1_qaa_notes_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qaa-meeting-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_api_v1_qaa_meeting_notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_api_v1_qaa_meeting_notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qaa-meeting-notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_v1_qaa_meeting_notes__note_id__delete"];
        options?: never;
        head?: never;
        /** Update Note */
        patch: operations["update_note_api_v1_qaa_meeting_notes__note_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/seed-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Reset
         * @description Drop all tables, recreate schema, load demo seed. Demo-only.
         */
        post: operations["seed_reset_api_v1_admin_seed_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AngelAbsent */
        AngelAbsent: {
            /** Absent */
            absent: boolean;
        };
        /** AngelCreate */
        AngelCreate: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Department Id */
            department_id?: string | null;
        };
        /** AngelOut */
        AngelOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Name */
            name: string;
            /** Department Id */
            department_id?: string | null;
            /** Department */
            department?: string | null;
            /** Absent */
            absent: boolean;
            /** Absent Since */
            absent_since?: string | null;
            /**
             * Resident Count
             * @default 0
             */
            resident_count: number;
        };
        /** AngelStat */
        AngelStat: {
            /**
             * Angel Id
             * Format: uuid
             */
            angel_id: string;
            /** Angel Name */
            angel_name: string;
            /** Round Count */
            round_count: number;
            /** Flags Raised */
            flags_raised: number;
        };
        /** DailyStat */
        DailyStat: {
            /** Date */
            date: string;
            /** Rounds */
            rounds: number;
        };
        /** DepartmentCreate */
        DepartmentCreate: {
            /** Name */
            name: string;
            /** Facility Id */
            facility_id?: string | null;
            /**
             * Custom
             * @default false
             */
            custom: boolean;
        };
        /** DepartmentOut */
        DepartmentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Facility Id */
            facility_id: string | null;
            /** Custom */
            custom: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IssueNotificationOut */
        IssueNotificationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Issue Id
             * Format: uuid
             */
            issue_id: string;
            /**
             * Notified User Id
             * Format: uuid
             */
            notified_user_id: string;
            /** Notified User Name */
            notified_user_name?: string | null;
            /**
             * Notified At
             * Format: date-time
             */
            notified_at: string;
            /** Channel */
            channel: string;
        };
        /** IssueOut */
        IssueOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Round Id */
            round_id?: string | null;
            /** Question Id */
            question_id?: string | null;
            /** Resident Id */
            resident_id?: string | null;
            /** Angel Id */
            angel_id?: string | null;
            /** Department Id */
            department_id?: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Resolved By */
            resolved_by?: string | null;
            /** Resolution Notes */
            resolution_notes?: string | null;
            /** Resident Name */
            resident_name?: string | null;
            /** Room */
            room?: string | null;
            /** Bed */
            bed?: string | null;
            /** Angel Name */
            angel_name?: string | null;
            /** Department Name */
            department_name?: string | null;
            /** Question Text */
            question_text?: string | null;
            /** Resolved By Name */
            resolved_by_name?: string | null;
            /**
             * Notifications
             * @default []
             */
            notifications: components["schemas"]["IssueNotificationOut"][];
        };
        /** IssueResolve */
        IssueResolve: {
            /**
             * Resolved By
             * Format: uuid
             */
            resolved_by: string;
            /** Resolution Notes */
            resolution_notes: string;
        };
        /** QaaMeetingNoteCreate */
        QaaMeetingNoteCreate: {
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
        };
        /** QaaMeetingNoteOut */
        QaaMeetingNoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Facility Id */
            facility_id?: string | null;
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QaaMeetingNoteUpdate */
        QaaMeetingNoteUpdate: {
            /** Meeting Date */
            meeting_date?: string | null;
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
        };
        /** QaaNoteOut */
        QaaNoteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Facility Id */
            facility_id?: string | null;
            /** Content */
            content: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QaaNoteUpdate */
        QaaNoteUpdate: {
            /** Content */
            content: string;
        };
        /** QapiCreate */
        QapiCreate: {
            /** Title */
            title: string;
            /**
             * Issues Identified
             * @default
             */
            issues_identified: string;
            /** Date Identified */
            date_identified?: string | null;
        };
        /** QapiItemCreate */
        QapiItemCreate: {
            /** Title */
            title: string;
            /**
             * Root Cause
             * @default
             */
            root_cause: string;
            /**
             * Systemic Change
             * @default
             */
            systemic_change: string;
            /**
             * Monitoring Type
             * @default rounds
             * @enum {string}
             */
            monitoring_type: "rounds" | "completion" | "cadence";
            /**
             * Monitoring Detail
             * @default
             */
            monitoring_detail: string;
            /**
             * Responsible
             * @default
             */
            responsible: string;
            /** Start Date */
            start_date?: string | null;
            /** Expected Completion */
            expected_completion?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** QapiItemOut */
        QapiItemOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Qapi Id
             * Format: uuid
             */
            qapi_id: string;
            /** Title */
            title: string;
            /**
             * Root Cause
             * @default
             */
            root_cause: string;
            /**
             * Systemic Change
             * @default
             */
            systemic_change: string;
            /**
             * Monitoring Type
             * @default rounds
             */
            monitoring_type: string;
            /**
             * Monitoring Detail
             * @default
             */
            monitoring_detail: string;
            /**
             * Responsible
             * @default
             */
            responsible: string;
            /** Start Date */
            start_date?: string | null;
            /** Expected Completion */
            expected_completion?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** QapiItemUpdate */
        QapiItemUpdate: {
            /** Title */
            title?: string | null;
            /** Root Cause */
            root_cause?: string | null;
            /** Systemic Change */
            systemic_change?: string | null;
            /** Monitoring Type */
            monitoring_type?: ("rounds" | "completion" | "cadence") | null;
            /** Monitoring Detail */
            monitoring_detail?: string | null;
            /** Responsible */
            responsible?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Expected Completion */
            expected_completion?: string | null;
            /** Order */
            order?: number | null;
        };
        /** QapiOut */
        QapiOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /**
             * Issues Identified
             * @default
             */
            issues_identified: string;
            /** Date Identified */
            date_identified?: string | null;
            /** Actual Completion */
            actual_completion?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["QapiItemOut"][];
        };
        /** QapiUpdate */
        QapiUpdate: {
            /** Title */
            title?: string | null;
            /** Status */
            status?: ("active" | "archived") | null;
            /** Issues Identified */
            issues_identified?: string | null;
            /** Date Identified */
            date_identified?: string | null;
            /** Actual Completion */
            actual_completion?: string | null;
        };
        /** QuestionCreate */
        QuestionCreate: {
            /** Text */
            text: string;
            /**
             * Section
             * @default
             */
            section: string;
            /**
             * Issue On
             * @default either
             * @enum {string}
             */
            issue_on: "yes" | "no" | "either";
            /** Notify Department Id */
            notify_department_id?: string | null;
            /** Department Id */
            department_id?: string | null;
            /**
             * Type
             * @default yesno
             * @enum {string}
             */
            type: "yesno" | "scale";
            /** Scale Min */
            scale_min?: number | null;
            /** Scale Max */
            scale_max?: number | null;
            /** Scale Threshold */
            scale_threshold?: number | null;
            /** Scale Threshold Direction */
            scale_threshold_direction?: ("gte" | "lte") | null;
            /**
             * In Repository
             * @default false
             */
            in_repository: boolean;
        };
        /** QuestionOut */
        QuestionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Text */
            text: string;
            /**
             * Section
             * @default
             */
            section: string;
            /** Issue On */
            issue_on: string;
            /** Notify Department Id */
            notify_department_id?: string | null;
            /** Department Id */
            department_id?: string | null;
            /**
             * Type
             * @default yesno
             */
            type: string;
            /** Scale Min */
            scale_min?: number | null;
            /** Scale Max */
            scale_max?: number | null;
            /** Scale Threshold */
            scale_threshold?: number | null;
            /** Scale Threshold Direction */
            scale_threshold_direction?: string | null;
            /** In Repository */
            in_repository: boolean;
        };
        /** QuestionUpdate */
        QuestionUpdate: {
            /** Text */
            text?: string | null;
            /** Section */
            section?: string | null;
            /** Issue On */
            issue_on?: ("yes" | "no" | "either") | null;
            /** Notify Department Id */
            notify_department_id?: string | null;
            /** Department Id */
            department_id?: string | null;
            /** Type */
            type?: ("yesno" | "scale") | null;
            /** Scale Min */
            scale_min?: number | null;
            /** Scale Max */
            scale_max?: number | null;
            /** Scale Threshold */
            scale_threshold?: number | null;
            /** Scale Threshold Direction */
            scale_threshold_direction?: ("gte" | "lte") | null;
            /** In Repository */
            in_repository?: boolean | null;
        };
        /** ReportOut */
        ReportOut: {
            /** Total Rounds */
            total_rounds: number;
            /** Total Flags */
            total_flags: number;
            /** Open Issues */
            open_issues: number;
            /** Resolved Issues */
            resolved_issues: number;
            /** Angel Stats */
            angel_stats: components["schemas"]["AngelStat"][];
            /** Daily Stats */
            daily_stats: components["schemas"]["DailyStat"][];
        };
        /** ResidentAssign */
        ResidentAssign: {
            /** Angel Id */
            angel_id: string | null;
        };
        /** ResidentCreate */
        ResidentCreate: {
            /** Name */
            name: string;
            /** Room */
            room: string;
            /**
             * Bed
             * @default a
             */
            bed: string;
            /** Angel Id */
            angel_id?: string | null;
            /** Pcc Id */
            pcc_id?: string | null;
        };
        /** ResidentGroupCreate */
        ResidentGroupCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @default custom
             * @enum {string}
             */
            type: "wing" | "cart" | "custom";
            /** Facility Id */
            facility_id?: string | null;
        };
        /** ResidentGroupMembershipUpdate */
        ResidentGroupMembershipUpdate: {
            /** Resident Ids */
            resident_ids: string[];
        };
        /** ResidentGroupOut */
        ResidentGroupOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Facility Id */
            facility_id?: string | null;
            /**
             * Member Ids
             * @default []
             */
            member_ids: string[];
        };
        /** ResidentGroupUpdate */
        ResidentGroupUpdate: {
            /** Name */
            name?: string | null;
            /** Type */
            type?: ("wing" | "cart" | "custom") | null;
        };
        /** ResidentOut */
        ResidentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Room */
            room: string;
            /** Bed */
            bed: string;
            /** Angel Id */
            angel_id?: string | null;
            /** Original Angel Id */
            original_angel_id?: string | null;
            /** Status */
            status: string;
            /** Pcc Id */
            pcc_id?: string | null;
        };
        /**
         * RoundAnswerOut
         * @description Lean answer payload bundled with a Round so the dashboard can compute
         *     QAPI compliance client-side without a follow-up fetch per round.
         */
        RoundAnswerOut: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Answer */
            answer?: boolean | null;
            /** Answer Number */
            answer_number?: number | null;
            /**
             * Issue Flagged
             * @default false
             */
            issue_flagged: boolean;
        };
        /** RoundAnswerSubmit */
        RoundAnswerSubmit: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Answer */
            answer?: boolean | null;
            /** Answer Number */
            answer_number?: number | null;
            /**
             * Issue Flagged
             * @default false
             */
            issue_flagged: boolean;
        };
        /** RoundOut */
        RoundOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /**
             * Angel Id
             * Format: uuid
             */
            angel_id: string;
            /**
             * Resident Id
             * Format: uuid
             */
            resident_id: string;
            /** Completed At */
            completed_at?: string | null;
            /** Angel Name */
            angel_name?: string | null;
            /** Resident Name */
            resident_name?: string | null;
            /** Resident Room */
            resident_room?: string | null;
            /** Template Name */
            template_name?: string | null;
            /**
             * Flags Raised
             * @default 0
             */
            flags_raised: number;
            /**
             * Answers
             * @default []
             */
            answers: components["schemas"]["RoundAnswerOut"][];
        };
        /** RoundSubmit */
        RoundSubmit: {
            /**
             * Template Id
             * Format: uuid
             */
            template_id: string;
            /**
             * Angel Id
             * Format: uuid
             */
            angel_id: string;
            /**
             * Resident Id
             * Format: uuid
             */
            resident_id: string;
            /** Answers */
            answers: components["schemas"]["RoundAnswerSubmit"][];
        };
        /** RoundTemplateCreate */
        RoundTemplateCreate: {
            /** Name */
            name: string;
            /**
             * Type
             * @default angel
             * @enum {string}
             */
            type: "angel" | "rapid";
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
        };
        /** RoundTemplateOut */
        RoundTemplateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Active */
            active: boolean;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Archived At */
            archived_at?: string | null;
            /** Deployed At */
            deployed_at?: string | null;
            /**
             * Rapid Completion Count
             * @default 0
             */
            rapid_completion_count: number;
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["TemplateSectionOut"][];
        };
        /** RoundTemplateUpdate */
        RoundTemplateUpdate: {
            /** Name */
            name?: string | null;
            /** Active */
            active?: boolean | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Archived At */
            archived_at?: string | null;
        };
        /** TemplateQuestionCreate */
        TemplateQuestionCreate: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** TemplateQuestionOut */
        TemplateQuestionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /** Text */
            text: string;
            /**
             * Section
             * @default
             */
            section: string;
            /** Issue On */
            issue_on: string;
            /** Notify Department Id */
            notify_department_id?: string | null;
            /**
             * Type
             * @default yesno
             */
            type: string;
            /** Scale Min */
            scale_min?: number | null;
            /** Scale Max */
            scale_max?: number | null;
            /** Scale Threshold */
            scale_threshold?: number | null;
            /** Scale Threshold Direction */
            scale_threshold_direction?: string | null;
            /** Order */
            order: number;
        };
        /** TemplateSectionCreate */
        TemplateSectionCreate: {
            /** Title */
            title: string;
            /** Qapi Id */
            qapi_id?: string | null;
            /** Qapi Item Id */
            qapi_item_id?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
        };
        /** TemplateSectionOut */
        TemplateSectionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Qapi Id */
            qapi_id?: string | null;
            /** Qapi Item Id */
            qapi_item_id?: string | null;
            /** Order */
            order: number;
            /**
             * Questions
             * @default []
             */
            questions: components["schemas"]["TemplateQuestionOut"][];
        };
        /** TemplateSectionUpdate */
        TemplateSectionUpdate: {
            /** Title */
            title?: string | null;
            /** Qapi Id */
            qapi_id?: string | null;
            /** Qapi Item Id */
            qapi_item_id?: string | null;
            /** Order */
            order?: number | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "angel" | "charge_nurse" | "viewer";
            /** Department Id */
            department_id?: string | null;
            /**
             * Notification Prefs
             * @default {}
             */
            notification_prefs: {
                [key: string]: unknown;
            };
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Department Id */
            department_id?: string | null;
            /**
             * Notification Prefs
             * @default {}
             */
            notification_prefs: {
                [key: string]: unknown;
            };
            /** Active */
            active: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role?: ("admin" | "angel" | "charge_nurse" | "viewer") | null;
            /** Department Id */
            department_id?: string | null;
            /** Notification Prefs */
            notification_prefs?: {
                [key: string]: unknown;
            } | null;
            /** Active */
            active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_departments_api_v1_departments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentOut"][];
                };
            };
        };
    };
    create_department_api_v1_departments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_department_api_v1_departments__dept_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_residents_api_v1_residents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentOut"][];
                };
            };
        };
    };
    create_resident_api_v1_residents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_resident_api_v1_residents__resident_id__assign_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentAssign"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_assign_api_v1_residents_auto_assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sync_pcc_api_v1_residents_sync_pcc_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_groups_api_v1_resident_groups_get: {
        parameters: {
            query?: {
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentGroupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_group_api_v1_resident_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_group_api_v1_resident_groups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_group_api_v1_resident_groups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_members_api_v1_resident_groups__group_id__members_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidentGroupMembershipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResidentGroupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_angels_api_v1_angels_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngelOut"][];
                };
            };
        };
    };
    create_angel_api_v1_angels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AngelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_absent_api_v1_angels__angel_id__absent_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                angel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AngelAbsent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AngelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redistribute_api_v1_angels__angel_id__redistribute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                angel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_qapis_api_v1_qapis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QapiOut"][];
                };
            };
        };
    };
    create_qapi_api_v1_qapis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QapiCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QapiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_qapi_api_v1_qapis__qapi_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qapi_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_qapi_api_v1_qapis__qapi_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qapi_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QapiUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QapiOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_qapis__qapi_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qapi_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QapiItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QapiItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_qapis__qapi_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qapi_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_qapis__qapi_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qapi_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QapiItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QapiItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_v1_questions_get: {
        parameters: {
            query?: {
                in_repository?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_question_api_v1_questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_question_api_v1_questions__question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_question_api_v1_questions__question_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_issues_api_v1_issues_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_issue_api_v1_issues__issue_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_issue_api_v1_issues__issue_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_rounds_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundTemplateOut"][];
                };
            };
        };
    };
    create_template_api_v1_rounds_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_rounds_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_rounds_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deploy_template_api_v1_rounds_templates__template_id__deploy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_section_api_v1_rounds_templates__template_id__sections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateSectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_section_api_v1_rounds_sections__section_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_section_api_v1_rounds_sections__section_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateSectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateSectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_question_to_section_api_v1_rounds_sections__section_id__questions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateQuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateQuestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_question_from_section_api_v1_rounds_template_questions__template_question_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_question_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rounds_api_v1_rounds_get: {
        parameters: {
            query?: {
                angel_id?: string | null;
                resident_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_round_api_v1_rounds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_reports_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                angel_id?: string | null;
                resident_id?: string | null;
                qapi_id?: string | null;
                qapi_item_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notes_api_v1_qaa_notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaaNoteOut"];
                };
            };
        };
    };
    update_notes_api_v1_qaa_notes_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QaaNoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaaNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_v1_qaa_meeting_notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaaMeetingNoteOut"][];
                };
            };
        };
    };
    create_note_api_v1_qaa_meeting_notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QaaMeetingNoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaaMeetingNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_qaa_meeting_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_v1_qaa_meeting_notes__note_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QaaMeetingNoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QaaMeetingNoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_reset_api_v1_admin_seed_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
